name: Release

on:
  push:
    tags:
      - '*.*.*'
env:
  PYTHON_VERSION: '3.7'
  UPX_VERSION: '3.96'
  UPX_SOURCE: 'https://github.com/upx/upx/releases/download/v'

jobs:

  win32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      shell: bash
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x86'
    - name: Install PyInstaller and UPX
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv run pip install pyinstaller
        mkdir ./UPX && mkdir ./UPX/dist
        curl -sL -o ./UPX/upx-compress ${{ env.UPX_SOURCE }}${{ env.UPX_VERSION }}/upx-${{ env.UPX_VERSION }}-win32.zip
        unzip ./UPX/upx-compress -d ./UPX/dist/
    - name: Build 32-bit version with PyInstaller
      shell: bash
      run: |
        PYTHONOPTIMIZE=1 pipenv run pyinstaller --upx-exclude=vcruntime140.dll --upx-exclude=ucrtbase.dll -F -i ./resources/app.ico --clean --upx-dir=./UPX/dist/upx-${{ env.UPX_VERSION }}-win32/ -n avsrepo-32 avsrepo.py
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: avsrepo-32.exe
        path: dist/avsrepo-32.exe
  win64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      shell: bash
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x64'
    - name: Install PyInstaller and UPX
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv run pip install pyinstaller
        mkdir ./UPX && mkdir ./UPX/dist
        curl -sL -o ./UPX/upx-compress ${{ env.UPX_SOURCE }}${{ env.UPX_VERSION }}/upx-${{ env.UPX_VERSION }}-win64.zip
        unzip ./UPX/upx-compress -d ./UPX/dist/
    - name: Build 64-bit version with PyInstaller
      shell: bash
      run: |
        PYTHONOPTIMIZE=1 pipenv run pyinstaller --upx-exclude=vcruntime140.dll --upx-exclude=ucrtbase.dll -F -i ./resources/app.ico --clean --upx-dir=./UPX/dist/upx-${{ env.UPX_VERSION }}-win64/ -n avsrepo-64 avsrepo.py
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: avsrepo-64.exe
        path: dist/avsrepo-64.exe


  Release:
    needs: [win32, win64]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Download 32-bit Windows release file
        uses: actions/download-artifact@master
        with:
          name: avsrepo-32.exe
          path: ./
      - name: Download 64-bit Windows release file
        uses: actions/download-artifact@master
        with:
          name: avsrepo-64.exe
          path: ./
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload 32-bit Windows release file asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: avsrepo-32.exe
          asset_name: avsrepo-32.exe
          asset_content_type: application/x-msdownload
      - name: Upload 64-bit Windows release file asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: avsrepo-64.exe
          asset_name: avsrepo-64.exe
          asset_content_type: application/x-msdownload
